---

- name: Enable Fastestmirror plugin
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: True

- name: Install Google Chrome repository
  yum_repository:
    name: google-chrome
    file: google-chrome
    description: google-chrome
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: true

- name: Install VSCode repository
  yum_repository:
    name: code
    file: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: true

- name: Install PlayOnLinux repository
  yum_repository:
    name: playonlinux
    file: playonlinux
    description: PlayOnLinux Official repository
    baseurl: http://rpm.playonlinux.com/fedora/yum/base
    gpgcheck: false
    gpgkey: http://rpm.playonlinux.com/public.gpg
    enabled: true

- name: Install Docker CE repository
  yum_repository:
    name: docker-ce-stable
    file: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: true

- name: Install Free and Nonfree RPMFusion repositories
  dnf:
    name: "{{ workstation_rpmfusion_repositories }}"
    state: present
